--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/INFOMCPE/PluginDownloader
branches:
- master
projects:
  PluginDownloader:
    path: ""
    icon: https://infomcpe.ru/data/resource_icons/0/260.jpg
...
