---
#Данный плагин был создан Алексем Лозовягиным (http://vk.com/olekseyua)
#Plugin by INFOMCPE.RU(https://github.com/infomcpe)
#█──────██─█████─█─███─█─────█─███████─███████─█─█████─██─────██──────██───────██████─██████──█─────█─
#█─█████─██─███─██──█──██────█─█───────█─────█─█──███──█─█████─█─█████─█─████████████─█─────█─█─────█─
#█─█████─███─█─███──█──█─█───█─█───────█─────█─█─█─█─█─█─███████─█████─█─████████████─█─────█─█─────█─
#█──────█████─████──█──█──█──█─█████───█─────█─█─██─██─█─███████──────██─────████████─██████──█─────█─
#█─█████─████─████──█──█───█─█─█───────█─────█─█─█████─█─███████─███████─████████───█─█───█───█─────█─
#█─█████─████─████──█──█────██─█───────█─────█─█─█████─█─█████─█─███████─████████───█─█────█──█─────█─
#█──────█████─████─███─█─────█─█───────███████─█─█████─██─────██─███████───────██───█─█─────█──█████──
#█████████████████─────────────────────────────██████████████████████████████████████─────────────────


#↓Set language available: ru, en, jp
#↓выбор языка доступно: ru, en, jp
lang: ru
#↓Service available: infomcpe.ru, pocketmine.net, imagicalmine.net
#↓Выбор сервиса доступно: infomcpe.ru, pocketmine.net, imagicalmine.net
service: infomcpe.ru
#↓Automatic updates of the plugin
#↓Автоматическое обновление данного плагина
Auto-Update: true
#↑WIP
#↑Не работает
...
