---
#Данный плагин был создан Алексем Лозовягиным (http://vk.com/olekseyua)
#Plugin by INFOMCPE.RU(https://github.com/infomcpe)
#█──────██─█████─█─███─█─────█─███████─███████─█─█████─██─────██──────██───────██████─██████──█─────█─
#█─█████─██─███─██──█──██────█─█───────█─────█─█──███──█─█████─█─█████─█─████████████─█─────█─█─────█─
#█─█████─███─█─███──█──█─█───█─█───────█─────█─█─█─█─█─█─███████─█████─█─████████████─█─────█─█─────█─
#█──────█████─████──█──█──█──█─█████───█─────█─█─██─██─█─███████──────██─────████████─██████──█─────█─
#█─█████─████─████──█──█───█─█─█───────█─────█─█─█████─█─███████─███████─████████───█─█───█───█─────█─
#█─█████─████─████──█──█────██─█───────█─────█─█─█████─█─█████─█─███████─████████───█─█────█──█─────█─
#█──────█████─████─███─█─────█─█───────███████─█─█████─██─────██─███████───────██───█─█─────█──█████──
#█████████████████─────────────────────────────██████████████████████████████████████─────────────────


#↓Set language available: ru, en
#↓выбор языка доступно: ru, en
lang: ru
#↓Service available: infomcpe.ru, pocketmine.net
#↓Выбор сервиса доступно: infomcpe.ru, pocketmine.net
service: infomcpe.ru
...
